### ISSUE TITLE
FFMPEGCV cannot process grayscale videos

### ISSUE THREAD

**Issue by akonanykhin** [parkpow/deep-license-plate-recognition#143] opened 2023-09-13 07:47 UTC
**Describe the bug**
FFMPEGCV in video-editor script cannot process grayscale videos.

**To Reproduce**
1. Send grayscale video to the script.
2. FFMPEGCV bugs out with `KeyError: 'nb_frames'` error on this line `cap = ffmpegcv.VideoCapture(video_path)`.

**Additional context**
Using cv2.VideoCapture instead works fine. Consider switching back to cv2 for reading frames?

**Comment by danleyb2** [comment] 2024-01-10 11:02
@akonanykhin @marcbelmont 
The **KeyError** is resolved by upgrading `ffmpegcv==0.3.8` at it was also the cause of #154 
However i lack a grayscale video that could reproduce the issue. Have tried converting using ffmpeg but no KeyError.
https://stackoverflow.com/a/32385256/3320006

**Comment by akonanykhin** [comment] 2024-01-10 11:33
@danleyb2 I used this video for testing:
https://drive.google.com/file/d/1RahC8Qr9tv4D4vUQ6-cpVSjyeQbS3nMR/view?usp=sharing
It seems KeyError is indeed resolved in 0.3.8.

**Closed** 2024-01-10 11:33 UTC
