### ISSUE TITLE
FFMPEGCV incorrectly reads video fps as 60 most of the time

### ISSUE THREAD

**Issue by akonanykhin** [parkpow/deep-license-plate-recognition#144] opened 2023-09-13 07:54 UTC
**Describe the bug**
FFMPEGCV incorrectly reads video fps as 60 most of the time.
This alters the speed of the videos produced by video-editor.

**To Reproduce**
1. `import ffmpegcv`
2. `cap = ffmpegcv.VideoCapture(video_path)`
3. `cap.fps`

**Expected behavior**
Should read correct fps.

**Additional context**
I've replaced it with normal OpenCV `fps_cap.get(cv2.CAP_PROP_FPS)`.
It works better, but also reports incorrect fps (like 2000) for some videos.
I've added `FPS` environment variable to override auto-detected one for such files, but we need some reliable solution.

**Comment by akonanykhin** [comment] 2023-11-06 07:19
Seems like `fps_cap.get(cv2.CAP_PROP_FPS)` only reports incorrect FPS for the version of OpenCV we're currently using. `4.7.0.72` does not have this problem. So rolling OpenCV back (or forward) could solve this issue.

**Comment by danleyb2** [comment] 2024-01-10 10:17
@akonanykhin Could you kindly share a test video of this? I have test several videos and unable to reproduce

**Comment by akonanykhin** [comment] 2024-01-10 10:30
@danleyb2 It's one of those 2:
https://drive.google.com/file/d/11le_bXaoZZtr0-sBRRsED4ZFYd0mT8jk/view?usp=sharing
https://drive.google.com/file/d/1JiCurUGvTVczErST2nruJyqyBCOWa5yD/view?usp=sharing

**Comment by danleyb2** [comment] 2024-01-10 11:02
@akonanykhin 
Videos don't have a defined **fps** defined but there is a **tbr** that can be a replacement.
Upgrading OpenCV resolves the issue but existing version of ffmpegcv didn't have the issue either.

Fprobe output:
```
Input #0, matroska,webm, from '/home/danleyb2/Work/platerecognizer/stream-test-videos/trinam.mkv':
  Metadata:
    encoder         : MilestoneMux
  Duration: 00:01:59.87, start: 0.000000, bitrate: 2259 kb/s
  Stream #0:0(eng): Video: h264 (Baseline), yuvj420p(pc, bt709, progressive), 1920x1080, SAR 1:1 DAR 16:9, 60 tbr, 1k tbn (default)
  Stream #0:1(eng): Video: mjpeg, none(bt470bg/unknown/unknown), 1920x1080, SAR 1:1 DAR 16:9, 1k tbr, 1k tbn (default)
```

**Comment by akonanykhin** [comment] 2024-01-10 11:10
@danleyb2 I don't think 60 is the correct fps for this video. VLC plays it at around 15, maybe even less, which feels correct. Is there no other way to determine fps?

**Comment by akonanykhin** [comment] 2024-01-10 11:20
@danleyb2 Here is another video, which actually has FPS of ~17, but ffmpegcv reads it as 60 again:
https://drive.google.com/file/d/1PTVJ0QJj1mzzvMisfR-h-E78yQI8pxBp/view?usp=sharing

**Comment by akonanykhin** [comment] 2024-01-10 11:35
@danleyb2 In this video ffmpegcv reads FPS as 25, when in reality it is 12:
https://drive.google.com/file/d/1RahC8Qr9tv4D4vUQ6-cpVSjyeQbS3nMR/view?usp=sharing

**Comment by danleyb2** [comment] 2024-01-10 17:11
@akonanykhin I have been able to reproduce the issue, I am checking on an alternative way to get FPS.

**Comment by danleyb2** [comment] 2024-01-10 19:58
@akonanykhin @marcbelmont Kindly review PR again
Fixed by calculating FPS manually by counting frames for 500ms

**Closed** 2024-01-11 08:41 UTC
